###
POST http://localhost:8081/profile/create
Content-Type: application/json


{

   "name": "pep",
   "surName" :"gvardiola",
   "email" : "man_city.com",
   "phone" : "99894123456222"


}



###
POST http://localhost:8081/auth/login
Content-Type: application/json


{


  "email" : "ko'ppakcha.com",
  "phone" : "99894123456789"


}


###
POST http://localhost:8080/auth/login
Content-Type: application/json


{

  "phone" : "99894123456789",
  "password":"12345"


}

###
GET http://localhost:8080/init/initAdmin
Content-Type: application/json

{
  "phone" : "99894123456789",
  "password" : "12345"
}

###
POST http://localhost:8080/auth/login
Content-Type: application/json


{

  "phone" : "998947771177",
  "password":"123456"


}